### ISSUE TITLE
Loom does not compile with an error containing `invalid use of template-name 'SSLClient'` after v2.2.0 upgrade

### ISSUE THREAD

**Issue by prototypicalpro** [OPEnSLab-OSU/Loom#67]
After upgrading to v2.2.0, Loom may not compile any sketch, generating an error that looks something like:
```
...
C:\Users\User\Documents\Arduino\libraries\Loom\src/InternetPlats/InternetPlat.h:44:10: error: invalid use of template-name 'SSLClient' without an argument list

  virtual SSLClient& get_client() = 0;

          ^~~~~~~~~
...
```
This is a known issue due to incompatible versions of SSLClient. To fix this issue, you will need to upgrade your SSLClient library to a version above v1.3.0. Do not apply this fix unless you will/have already upgraded your Loom library to >v2.2.0, as the newer versions of SSLClient will not compile with older versions of Loom. 

To upgrade your SSLClient library:
1. Navigate to the Arduino Library Manager (`Sketch->Include Library->Manage Libraries...`) and wait for the window to load.
1. Enter `SSLClient` into the search box and press enter.
1. Click on the update button on the item labeled `SSLClient`.

If you continue to have issues after completing these instructions, please file another issue.

**Comment by MrKangs** [comment]
@prototypicalpro  Is this bug still exists? If you, can you tell me where?

**Comment by prototypicalpro** [comment]
This issue has been resolved with newer versions Loom and SSLClient. I left this issue open as a reminder for people to ensure they upgrade SSLClient while upgrading Loom, however there is probably no need for it anymore now that most of the lab has upgraded. I will go ahead and close it.
